#!/bin/bash

# 🔧 QUICK FIX: Thiết lập Google Gemini API Key
echo "🚨 PHÁT HIỆN THIẾU API KEY!"
echo ""
echo "🎯 VẤN ĐỀ: Backend cần Google Gemini API key để:"
echo "   ✨ Writing Practice Service"
echo "   ✨ AI Evaluation"
echo "   ✨ Example Sentence Generation"
echo ""
echo "🔧 CÁCH SỬA (NHANH - 2 PHÚT):"
echo ""
echo "1️⃣ Mở trình duyệt và truy cập:"
echo "   👉 https://aistudio.google.com/app/apikey"
echo ""
echo "2️⃣ Đăng nhập tài khoản Google của bạn"
echo ""
echo "3️⃣ Click nút 'Create API Key' màu xanh"
echo ""
echo "4️⃣ Chọn project (hoặc tạo mới nếu chưa có)"
echo ""
echo "5️⃣ Copy API key (dạng: AIza...)"
echo ""
echo "6️⃣ Chạy lệnh sau (thay YOUR_API_KEY):"
echo "   export GEMINI_API_KEY='AIza_YOUR_ACTUAL_KEY_HERE'"
echo ""
echo "7️⃣ Restart backend:"
echo "   cd /Users/manhkien/Documents/DATN_HMK/Smart-Flashcard-BE"
echo "   pkill -f spring-boot"
echo "   ./mvnw spring-boot:run"
echo ""
echo "✅ Xong! Backend sẽ hoạt động đầy đủ."
echo ""
echo "💡 LƯU Ý:"
echo "   • API key MIỄN PHÍ"
echo "   • Có giới hạn: 15 requests/phút"
echo "   • Không cần thẻ tín dụng"
echo "   • Chỉ cần tài khoản Google"
echo ""
echo "🔍 KIỂM TRA API key hiện tại:"
if [ -z "$GEMINI_API_KEY" ]; then
    echo "   ❌ GEMINI_API_KEY: CHƯA CẤU HÌNH"
else
    echo "   ✅ GEMINI_API_KEY: ${GEMINI_API_KEY:0:20}..."
fi
echo ""
echo "📞 Nếu cần hỗ trợ, cung cấp API key để tôi giúp setup!"
