server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: elearning-service
  
  # H2 Database Configuration for Testing
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    hikari:
      idle-timeout: 30000
      maximum-pool-size: 10
  
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  mvc:
    path-match:
      matching-strategy: ant_path_matcher
  
  jackson:
    time-zone: Asia/Ho_Chi_Minh
    date-format: yyyy-MM-dd HH:mm:ss

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

# JWT Configuration
jwt:
  secret: your-secret-key-here-at-least-256-bits-long-for-security
  expiration: 86400000

# Logging
logging:
  level:
    root: INFO
    com.elearning: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
